# Generated by Django 5.1.5 on 2025-02-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', 'xxxx_restore_contact_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='message_count',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='offer_count',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='view_count',
        ),
    ]
