# Generated by Django 5.1.5 on 2025-02-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='allow_offers',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='model',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='negotiable',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='show_phone',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='year',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='offer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='offers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
