# Generated by Django 5.1.5 on 2025-02-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_alter_location_city_alter_location_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifieds.location'),
        ),
    ]
